config/routes.rb
Rails.application.routes.draw do
  # デバイス
  devise_for :customers, skip: :all
  devise_scope :customer do
    get '/customers/sign_in', to: 'customers/sessions#new'
    post '/customers/sign_in', to: 'customers/sessions#create'
    delete '/customers/sign_out', to: 'customers/sessions#destroy'
    get '/customers/sign_up', to: 'customers/registrations#new'
    post '/customers', to: 'customers/registrations#create'
    get '/password/edit', to: 'customers/registrations#edit'
    put '/password/update', to: 'customers/passwords#update'
  end

  #ルート設定
  root "products#top"

  #顧客
  resource :customers, only: [:show,:edit,:update] do
    get :leave, on: :collection
    patch :left, on: :member
  end
  namespace :admin do
    resources :customers, only: [:index,:show,:edit,:update]
  end

  #管理者ログイン
  namespace :admin do
    get '/sign_in', to: 'admin#new'
    post '/sign_in', to: 'admin#create'
    delete '/sign_out', to: 'admin#destroy'
    get '/', to: 'admin#index'
  end

  #商品
  resources :products, only: [:index,:show] do
    get :top, on: :collection
  end
  namespace :admin do
    resources :products, only: [:index,:new,:show,:edit,:create,:update]
  end

  #配送先
  resources :ships, only: [:index,:edit,:update,:create,:destroy]

  #ジャンル
  namespace :admin do
    resources :genres, only: [:index,:edit,:update,:create]
  end

  #カートの商品
  post '/cart_products', to: 'cart_products#add'
  resources :cart_products, only: [:index,:destroy,:update] do
    delete :destroy_all, on: :collection
  end

  # 注文
  resources :orders, only: [:index,:show,:new,:create] do
    post :confirmation, action: :confirmation_new, on: :new
    get :complete, on: :collection
  end
  namespace :admin do
    resources :orders, only: [:index,:show,:update]
    patch '/order_products/:id', to: 'orders#products_update'
  end

  # 検索コーナー
  namespace :admin do
    get 'search/index', as: 'search'
  end



end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :customer
  belongs_to :product, optional: true

  validates :quantity, presence: true
end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController
  before_action :authenticate_customer!

  def add
    @cart_product = current_cart.cart_products.find_by(product_id: params[:product_id])
    if @cart_product&.product_id.nil?
      @cart_product = current_cart.cart_products.build(cart_product_params)
      if @cart_product.quantity.nil?
        redirect_back(fallback_location: root_path)
        return
      end
      @cart_product.save
      redirect_to cart_products_path
    else
      @cart_product.quantity += params[:cart_product][:quantity].to_i
      @cart_product.save
      redirect_to cart_products_path
    end
  end

  def index
    @cart_products = current_cart.cart_products
    @total_price = 0
    @cart_products.each do |cart_product|
      product_quantity = cart_product.quantity
      sub_total = product_quantity * cart_product.product.non_taxed_price
      @total_price += sub_total
    end
    @total_price *= 1.1
  end

  def destroy
    cart_product = current_cart.cart_products.find_by(product_id: params[:id])
    cart_product.destroy
    redirect_to cart_products_path
  end

  def destroy_all
    cart_products = current_cart.cart_products
    cart_products.each do |cart_product|
      cart_product.destroy
    end
    redirect_to cart_products_path
  end

  def update
    @cart_products = current_customer.cart_products
    @cart_product = current_cart.cart_products.find_by(product_id: params[:id])
    @cart_product.update(cart_product_params)
    unless request.referer.include?("/orders/new/confirmation")
      redirect_to cart_products_path
    end
  end

  private
  def cart_product_params
    params.require(:cart_product).permit(:product_id,:quantity,:customer_id)
  end

end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/views/cart_products/_confirmation_new.html.erb
<!-- カートの商品 -->
  <div class="col-sm-7">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th class="table-info">商品名</th>
          <th class="table-info">単価(税込)</th>
          <th class="table-info">数量</th>
          <th class="table-info">小計</th>
        </tr>
      </thead>
      <tbody>
        <% @total_price = 0 %>
        <% @cart_products.each do |cart| %>
          <tr>
            <td class="table-light align-middle">
              <%= attachment_image_tag cart.product, :image, :fill, 50, 50, format: 'jpeg'%>
              <%= cart.product&.name %>
            </td>
            <td class="table-light align-middle">
              <% tax_price = cart.product.non_taxed_price * 1.1 %>
              <%= comma_price(tax_price) %>
            </td>
            <td class="table-light align-middle">
              <%= form_with model: cart, url: cart_product_path(cart.product.id), method: :patch do |f| %>
                <%= f.number_field :quantity, min:1, step: 1, style: "width: 60px;", class: "form-control float-left" %>
                <%= f.submit '変更', class: "btn btn-primary btn-sm float-left mt-1" %>
              <% end %>
            </td>
            <% subtotal = tax_price * cart.quantity %>
            <td class="table-light align-middle"><%= comma_price(subtotal) %></td>
          </tr>
          <% @total_price += subtotal %>
        <% end %>
      </tbody>
    </table>
  </div>

  <!-- 金額情報テーブル -->
  <div class="col-sm-4 pl-5">
    <table class="table table-bordered">
      <tbody>
        <tr>
          <th class="table-info">送料</th>
          <td class="table-light">800</td>
        </tr>
        <tr>
          <th class="table-info">商品合計</th>
          <td class="table-light"><%= comma_price(@total_price) %></td>
        </tr>
        <tr>
          <th class="table-info">請求金額</th>
          <td class="table-light"><%= billion_price(@total_price) %></td>
        </tr>
      </tbody>
    </table>
  </div>

app/views/cart_products/index.html.erb
<div class="row">
  <div class="col-sm">
    <h5><span>ショッピングカート</span></h5>
  </div>
  <div class="col-sm-right pr-3 pt-5">
    <%= link_to 'カートを空にする', destroy_all_cart_products_path, method: :delete, class: "btn btn-danger btn-sm" %>
  </div>
</div>

<div class="row mt-3">
  <!-- カートテーブル -->
  <table class="table table-bordered">
    <thead>
      <tr class="table-info">
        <th>商品名</th>
        <th>単価(税込)</th>
        <th>数量</th>
        <th>小計</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @cart_products.each do |cart| %>
      <tr>
        <td class="table-light align-middle">
          <%= attachment_image_tag cart.product, :image, :fill, 50, 50, format: 'jpeg'%>
          <%= cart.product&.name %>
        </td>
        <td class="table-light align-middle">
          <% tax_price = cart.product.non_taxed_price * 1.1 %>
          <%= tax_price.floor.to_s(:delimited) %>
        </td>
        <td class="table-light align-middle">
          <%= form_with model: cart, url: cart_product_path(cart.product.id), method: :patch, local: true do |f| %>
            <%= f.number_field :quantity, min:1, step: 1, style: "width: 60px;", class: "form-control float-left" %>
            <%= f.submit '変更', class: "btn btn-primary btn-sm float-left mt-1" %>
          <% end %>
        </td class="table-light align-middle">
        <% subtotal = tax_price * cart.quantity %>
        <td class="table-light align-middle"><%= subtotal.floor.to_s(:delimited) %></td>
        <td class="table-light text-center"><%= link_to '削除する', cart_product_path(cart.product.id), method: :delete, class: "btn btn-danger btn-sm" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="row">
  <div class="col-sm">
    <%= link_to '買い物を続ける', root_path, class: "btn btn-info btn-sm" %>
  </div>

  <!-- 合計金額テーブル -->
  <div class="col-sm-3 float-right">
    <table class="table table-bordered ">
      <tbody>
        <tr>
          <th class="table-info">合計金額</th>
          <td class="table-light"><%= @total_price.floor.to_s(:delimited) %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-sm">
    <% if @cart_products.present? %>
      <div class="row" style="text-align: center;">
          <div class="col-md-4 offset-md-4">
            <%= link_to '情報入力に進む', new_order_path, class: "btn btn-success" %>
          </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cart_products/update.js.erb
$("#cart_table").html("<%= j(render 'cart_products/confirmation_new', {cart_products: @cart_products, order: @order}) %>");