config/routes.rb
Rails.application.routes.draw do
  # デバイス
  devise_for :customers, skip: :all
  devise_scope :customer do
    get '/customers/sign_in', to: 'customers/sessions#new'
    post '/customers/sign_in', to: 'customers/sessions#create'
    delete '/customers/sign_out', to: 'customers/sessions#destroy'
    get '/customers/sign_up', to: 'customers/registrations#new'
    post '/customers', to: 'customers/registrations#create'
    get '/password/edit', to: 'customers/registrations#edit'
    put '/password/update', to: 'customers/passwords#update'
  end

  #ルート設定
  root "products#top"

  #顧客
  resource :customers, only: [:show,:edit,:update] do
    get :leave, on: :collection
    patch :left, on: :member
  end
  namespace :admin do
    resources :customers, only: [:index,:show,:edit,:update]
  end

  #管理者ログイン
  namespace :admin do
    get '/sign_in', to: 'admin#new'
    post '/sign_in', to: 'admin#create'
    delete '/sign_out', to: 'admin#destroy'
    get '/', to: 'admin#index'
  end

  #商品
  resources :products, only: [:index,:show] do
    get :top, on: :collection
  end
  namespace :admin do
    resources :products, only: [:index,:new,:show,:edit,:create,:update]
  end

  #配送先
  resources :ships, only: [:index,:edit,:update,:create,:destroy]

  #ジャンル
  namespace :admin do
    resources :genres, only: [:index,:edit,:update,:create]
  end

  #カートの商品
  post '/cart_products', to: 'cart_products#add'
  resources :cart_products, only: [:index,:destroy,:update] do
    delete :destroy_all, on: :collection
  end

  # 注文
  resources :orders, only: [:index,:show,:new,:create] do
    post :confirmation, action: :confirmation_new, on: :new
    get :complete, on: :collection
  end
  namespace :admin do
    resources :orders, only: [:index,:show,:update]
    patch '/order_products/:id', to: 'orders#products_update'
  end

  # 検索コーナー
  namespace :admin do
    get 'search/index', as: 'search'
  end



end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, :introduction, presence: { message: ':必ず1文字以上入力してください。' }
	validates :image, presence: { message: ':必ず画像を選択してください。' }
	validates :genre_id, presence: { message: ':必ず選択してください。' }
	validates :has_sold, inclusion: { in: [true, false], message: ':必ず選択してください。' }
	validates :name, uniqueness: true
	validates :non_taxed_price,numericality: { only_integer: true, message: ':必ず半角の整数で入力してください。' }

	belongs_to :genre
	attachment :image
	has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products
  has_many :cart_products, dependent: :destroy

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin

  def index
    products = Product.includes(:genre).where(genres: {is_valid: "true"})
    @products= Kaminari.paginate_array(products).page(params[:page])
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if
    #binding.pry
      @product.save
      redirect_to admin_product_path(@product)
    else
      @error = @product.errors.full_messages
      if @error.include?("ジャンルを入力してください")
        @error.delete("ジャンルを入力してください")
      end
    # if @error.include?("Genreを入力してください")
    # @error.delete("Genreを入力してください")
    # @error.push("ジャンルを入力してください")
    # @error_class = 1
      render :new
    #end
    end
  end

  def update
    @product = Product.find(params[:id])
    if
    @product.update(product_params)
    redirect_to admin_product_path(@product.id)
    else
    @error = @product.errors.full_messages
    if @error.include?("ジャンルを入力してください")
       @error.delete("ジャンルを入力してください")
    end
    render :edit
    end
  end
  end

  def destroy
  end


  private

  def product_params
    params.require(:product).permit( :image, :name, :introduction, :non_taxed_price, :has_sold, :genre_id, :genre_name, :is_valid )
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @genres = Genre.where(genres: {is_valid: "true"})
     products = Product.includes(:genre).where(genres: {is_valid: "true"}).where(has_sold: "true")
    @products = Kaminari.paginate_array(products).page(params[:page]).per(8)
    # urlにgenre_id(params)がある場合
    if params[:genre_id]
      # Genreのデータベースのテーブルから一致するidを取得
      genre = Genre.find(params[:genre_id])
      # genre_idと紐づく商品を取得
      products = genre.products.order(created_at: :desc).where(has_sold: "true")
      @products = Kaminari.paginate_array(products).page(params[:page]).per(8)
      @products_cnt = Product.count
      @products_name = genre.genre_name
    else
      # 投稿すべてを取得
      @products_cnt = Product.count
      products = Product.includes(:genre).where(genres: {is_valid: "true"}).where(has_sold: "true")
      @products = Kaminari.paginate_array(products).page(params[:page]).per(8)
      @products_name = "商品"
    end

  end

  def show
    @product = Product.find(params[:id])
    @cart_product = CartProduct.new
    @genres = Genre.where(genres: {is_valid: "true"})
  end

  def top
    @genres = Genre.where(genres: {is_valid: "true"})
    @products = Product.page(params[:page]).per(4).where(has_sold: "true")
  end

  private
  def product_params
    params.require(:product).permit(:genre_id, :name, :introduction, :image, :non_taxed_price, :has_sold)
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper

def sales(sales)
	if sales
		'販売中'
	else
		'販売停止中'
	end
end

def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}"
end

def addTax(money,rate)
   taxed_money = (money*rate).round
   "#{taxed_money.to_s(:delimited, delimiter: ',')}"
end

def jpy(price)
    "(#{price.to_s(:delimited, delimiter: ',')}）円"
end

def embedded_svg filename, options={}
    file = File.read(Rails.root.join('app', 'assets', 'images', filename))
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] = options[:class]
    end
    doc.to_html.html_safe
end

def yen
  "円"
end

end

app/helpers/products_helper.rb
module ProductsHelper

def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}"
end

def addTax(money,rate)
   taxed_money =  (money*rate).round
   "#{taxed_money.to_s(:delimited, delimiter: ',')}"

end

end

app/views/admin/products/edit.html.erb
<%= form_for(@product, url: admin_product_path(@product), html: {class: "form-horizontal"}) do |f| %>

<% if @product.errors.any? %>
  <div id="error_explanation" class="alert">
  	<h4><%= pluralize(@error.count, "個") %> のエラーがあります:</h4>
    <ul>
      <% @error.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="container">
	<h5><span>商品編集</span></h5>
	<div class="row mt-4">
	<div class="col-sm-5 d-flex flex-column align-items-center">
	<%= attachment_image_tag @product, :image, :fill, 290, 290, format: 'jpeg', class: "btn rounded-pill", fallback: "sample.jpeg" %>
	<div class =" mt-4">
	<%= f.attachment_field :image %>
	</div>
</div>

<div class="col-sm-6">

<div class="form-group row">
	<label class="col-sm-4 col-form-label d-flex flex-column align-items-end">
		<%= f.label :name %>
	</label>
	<div class="col-sm-7">
		<%= f.text_field :name, class: "form-control" %>
	</div>
</div>


<div class="form-group row mt-2">
	<label class="col-sm-4 col-form-label d-flex flex-column align-items-end">
		<%= f.label :introduction %>
	</label>
	<div class="col-sm-7">
		<%= f.text_area :introduction, class: "form-control", style: "height: 150px;" %>
	</div>
</div>


<div class="form-group row mt-2">
	<label class="col-sm-4 col-form-label d-flex flex-column align-items-end">
		<%= f.label :genre_id %>
	</label>
	<div class="col-sm-7">
		<%= f.collection_select :genre_id, Genre.all, :id, :genre_name, {prompt: "-- 選択してください --"}, {class: "custom-select"} %>
	</div>
</div>


<div class="form-group row mt-2">
	<label class="col-sm-4 col-form-label d-flex flex-column align-items-end">
		<%= f.label :non_taxed_price %>
	</label>
	<div class="col-sm-7">
		<%= f.text_field :non_taxed_price, placeholder: "円", style: "text-align: right;", class: "form-control" %>
	</div>
</div>


<div class="form-group row mt-2">
	<label class="col-sm-4 col-form-label d-flex flex-column align-items-end">
		<%= f.label :has_sold %>
	</label>
	<div class="col-sm-7">
		<%= f.select :has_sold, {'販売中': true, '販売停止中': false}, { prompt: "-- 選択してください --"}, { class: "custom-select"} %>
	</div>
</div>
</div>

<div class="col-sm-1 align-self-end mt-2">
<div class="actions">
	<%= f.submit "変更を保存", class: "btn btn-outline-light bg-dark rounded-pill btn-lg" %>
</div>
</div>
</div>
</div>

<% end %>

app/views/admin/products/index.html.erb
<h5><span>商品一覧</span></h5>

<div class="float-sm-right">
<%= link_to new_admin_product_path, style:"border-bottom: none;" do %>
  <%= embedded_svg("plus-circle.svg", class: "svg") %>
<% end %>
</div>

<table class="table">
  <thead>
    <tr class="table-info col text-center">
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr class="table-light col text-center">
        <td><%= product.id %></td>
        <td><%= link_to product.name, admin_product_path(product.id) %></td>
        <td><%= converting_to_jpy(product.non_taxed_price) %></td>
        <td><%= product.genre.genre_name %></td>
        <td><%= sales(product.has_sold) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

    <%= paginate @products %>

app/views/admin/products/new.html.erb
<%= form_for(@product, url: admin_products_path, html: {class: "form-horizontal"}) do |f| %>

<% if @product.errors.any? %>
  <div id="error_explanation" class="alert">
  	<h4><%= pluralize(@error.count, "個") %> のエラーがあります:</h4>
    <ul>
      <% @error.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="container">
	<h5><span>商品新規登録</span></h5>
	<div class="row mt-5">
	<div class="col-sm-5 d-flex flex-column align-items-center">

	<%= attachment_image_tag @product, :image, :fill, 300, 300, format: 'jpeg', class: "btn rounded-pill", fallback: "sample.jpeg" %>

	<div class =" mt-4">
	<%= f.attachment_field :image %>
	</div>
</div>

<div class="col-sm-6">

<div class="form-group row">
	<label class="col-sm-4 col-form-label d-flex flex-column align-items-end">
		<%= f.label :name %>
	</label>
	<div class="col-sm-7">
		<%= f.text_field :name, class: "form-control" %>
	</div>
</div>


<div class="form-group row mt-2">
	<label class="col-sm-4 col-form-label d-flex flex-column align-items-end">
		<%= f.label :introduction %>
	</label>
	<div class="col-sm-7">
		<%= f.text_area :introduction, class: "form-control", style: "height: 150px;" %>
	</div>
</div>


<div class="form-group row mt-2">
	<label class="col-sm-4 col-form-label d-flex flex-column align-items-end">
		<%= f.label :genre_id %>
	</label>
	<div class="col-sm-7">
		<%= f.collection_select :genre_id, Genre.all, :id, :genre_name, {prompt: "-- 選択してください --"}, {class: "custom-select"} %>
	</div>
</div>


<div class="form-group row mt-2">
	<label class="col-sm-4 col-form-label d-flex flex-column align-items-end">
		<%= f.label :non_taxed_price %>
	</label>
	<div class="col-sm-7">
		<%= f.text_field :non_taxed_price, placeholder: "円", style: "text-align: right;", class: "form-control" %>
	</div>
</div>


<div class="form-group row mt-2">
	<label class="col-sm-4 col-form-label d-flex flex-column align-items-end">
		<%= f.label :has_sold %>
	</label>
	<div class="col-sm-7">
		<%= f.select :has_sold, {'販売中': true, '販売停止中': false}, { prompt: "-- 選択してください --"}, { class: "custom-select"} %>
	</div>
</div>
</div>

<div class="col-sm-1 align-self-end mt-2">
<div class="actions">
	<%= f.submit "新規登録", class: "btn btn-outline-light bg-dark rounded-pill btn-lg" %>
</div>
</div>
</div>
</div>

<% end %>

app/views/admin/products/show.html.erb
<div class="container">
	<h5><span>商品詳細</span></h5>
	<div class="row mt-4">
	<div class="col-sm-5 d-flex flex-column align-items-center">
	<%= attachment_image_tag @product, :image, :fill, 300, 300, format: 'jpeg', class: "btn rounded-pill", fallback: "sample.jpeg" %>
</div>

	<div class="col-sm-6 mt-4">


<div class="form-group row">
	<div class="col-sm-4 col-form-label d-flex flex-column align-items-end">
		<em>商品名</em>
	</div>
	<div class="col-sm-7 d-flex flex-column align-self-center">
		<strong><%= @product.name %></strong>
	</div>
</div>


<div class="form-group row">
	<div class="col-sm-4 col-form-label d-flex flex-column align-items-end">
		<em>商品説明</em>
	</div>
	<div class="col-sm-7 d-flex flex-column align-self-center">
		<strong><%= simple_format(h(@product.introduction)) %></strong>
	</div>
</div>


<div class="form-group row">
	<div class="col-sm-4 col-form-label d-flex flex-column align-items-end">
		<em>ジャンル</em>
	</div>
	<div class="col-sm-7 d-flex flex-column align-self-center">
		<strong><%= @product.genre.genre_name %></strong>
	</div>
</div>


<div class="form-group row">
	<div class="col-sm-4 col-form-label d-flex flex-column align-items-end">
		<em>税込価格<br>(税抜価格)</em>
	</div>
	<div class="col-sm-7 d-flex flex-column align-self-center">
		<strong><%= addTax(@product.non_taxed_price,1.10) %> <%= yen %> <br>
		<%= jpy(@product.non_taxed_price) %></strong>
	</div>
</div>


<div class="form-group row">
	<div class="col-sm-4 col-form-label d-flex flex-column align-items-end">
		<em>販売ステータス</em>
	</div>
	<div class="col-sm-7 d-flex flex-column align-self-center">
		<strong><%= sales(@product.has_sold) %></strong>
	</div>
</div>

</div>
</div>

<div class="row">
	<div class="col-sm-11 d-flex flex-column align-items-end">
	<%= link_to "編集する",edit_admin_product_path(@product), class: "btn btn-outline-light bg-dark rounded-pill btn-lg edit_admin_product_#{@product.id}" %>
	</div>
</div>

</div>