config/routes.rb
Rails.application.routes.draw do
  # デバイス
  devise_for :customers, skip: :all
  devise_scope :customer do
    get '/customers/sign_in', to: 'customers/sessions#new'
    post '/customers/sign_in', to: 'customers/sessions#create'
    delete '/customers/sign_out', to: 'customers/sessions#destroy'
    get '/customers/sign_up', to: 'customers/registrations#new'
    post '/customers', to: 'customers/registrations#create'
    get '/password/edit', to: 'customers/registrations#edit'
    put '/password/update', to: 'customers/passwords#update'
  end

  #ルート設定
  root "products#top"

  #顧客
  resource :customers, only: [:show,:edit,:update] do
    get :leave, on: :collection
    patch :left, on: :member
  end
  namespace :admin do
    resources :customers, only: [:index,:show,:edit,:update]
  end

  #管理者ログイン
  namespace :admin do
    get '/sign_in', to: 'admin#new'
    post '/sign_in', to: 'admin#create'
    delete '/sign_out', to: 'admin#destroy'
    get '/', to: 'admin#index'
  end

  #商品
  resources :products, only: [:index,:show] do
    get :top, on: :collection
  end
  namespace :admin do
    resources :products, only: [:index,:new,:show,:edit,:create,:update]
  end

  #配送先
  resources :ships, only: [:index,:edit,:update,:create,:destroy]

  #ジャンル
  namespace :admin do
    resources :genres, only: [:index,:edit,:update,:create]
  end

  #カートの商品
  post '/cart_products', to: 'cart_products#add'
  resources :cart_products, only: [:index,:destroy,:update] do
    delete :destroy_all, on: :collection
  end

  # 注文
  resources :orders, only: [:index,:show,:new,:create] do
    post :confirmation, action: :confirmation_new, on: :new
    get :complete, on: :collection
  end
  namespace :admin do
    resources :orders, only: [:index,:show,:update]
    patch '/order_products/:id', to: 'orders#products_update'
  end

  # 検索コーナー
  namespace :admin do
    get 'search/index', as: 'search'
  end



end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, :introduction, presence: { message: ':必ず1文字以上入力してください。' }
	validates :image, presence: { message: ':必ず画像を選択してください。' }
	validates :genre_id, presence: { message: ':必ず選択してください。' }
	validates :has_sold, inclusion: { in: [true, false], message: ':必ず選択してください。' }
	validates :name, uniqueness: true
	validates :non_taxed_price,numericality: { only_integer: true, message: ':必ず半角の整数で入力してください。' }

	belongs_to :genre
	attachment :image
	has_many :order_products, dependent: :destroy
  has_many :orders, through: :order_products
  has_many :cart_products, dependent: :destroy

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin

  def index
    products = Product.includes(:genre).where(genres: {is_valid: "true"})
    @products= Kaminari.paginate_array(products).page(params[:page])
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    if
    #binding.pry
      @product.save
      redirect_to admin_product_path(@product)
    else
      @error = @product.errors.full_messages
      if @error.include?("ジャンルを入力してください")
        @error.delete("ジャンルを入力してください")
      end
    # if @error.include?("Genreを入力してください")
    # @error.delete("Genreを入力してください")
    # @error.push("ジャンルを入力してください")
    # @error_class = 1
      render :new
    #end
    end
  end

  def update
    @product = Product.find(params[:id])
    if
    @product.update(product_params)
    redirect_to admin_product_path(@product.id)
    else
    @error = @product.errors.full_messages
    if @error.include?("ジャンルを入力してください")
       @error.delete("ジャンルを入力してください")
    end
    render :edit
    end
  end
  end

  def destroy
  end


  private

  def product_params
    params.require(:product).permit( :image, :name, :introduction, :non_taxed_price, :has_sold, :genre_id, :genre_name, :is_valid )
  end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @genres = Genre.where(genres: {is_valid: "true"})
     products = Product.includes(:genre).where(genres: {is_valid: "true"}).where(has_sold: "true")
    @products = Kaminari.paginate_array(products).page(params[:page]).per(8)
    # urlにgenre_id(params)がある場合
    if params[:genre_id]
      # Genreのデータベースのテーブルから一致するidを取得
      genre = Genre.find(params[:genre_id])
      # genre_idと紐づく商品を取得
      products = genre.products.order(created_at: :desc).where(has_sold: "true")
      @products = Kaminari.paginate_array(products).page(params[:page]).per(8)
      @products_cnt = Product.count
      @products_name = genre.genre_name
    else
      # 投稿すべてを取得
      @products_cnt = Product.count
      products = Product.includes(:genre).where(genres: {is_valid: "true"}).where(has_sold: "true")
      @products = Kaminari.paginate_array(products).page(params[:page]).per(8)
      @products_name = "商品"
    end

  end

  def show
    @product = Product.find(params[:id])
    @cart_product = CartProduct.new
    @genres = Genre.where(genres: {is_valid: "true"})
  end

  def top
    @genres = Genre.where(genres: {is_valid: "true"})
    @products = Product.page(params[:page]).per(4).where(has_sold: "true")
  end

  private
  def product_params
    params.require(:product).permit(:genre_id, :name, :introduction, :image, :non_taxed_price, :has_sold)
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper

def sales(sales)
	if sales
		'販売中'
	else
		'販売停止中'
	end
end

def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}"
end

def addTax(money,rate)
   taxed_money = (money*rate).round
   "#{taxed_money.to_s(:delimited, delimiter: ',')}"
end

def jpy(price)
    "(#{price.to_s(:delimited, delimiter: ',')}）円"
end

def embedded_svg filename, options={}
    file = File.read(Rails.root.join('app', 'assets', 'images', filename))
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] = options[:class]
    end
    doc.to_html.html_safe
end

def yen
  "円"
end

end

app/helpers/products_helper.rb
module ProductsHelper

def converting_to_jpy(price)
    "#{price.to_s(:delimited, delimiter: ',')}"
end

def addTax(money,rate)
   taxed_money =  (money*rate).round
   "#{taxed_money.to_s(:delimited, delimiter: ',')}"

end

end

app/views/products/index.html.erb
<div class="row">
	<div class="col-sm-2 mt-4">
		<table border="1">
    		<thead>
        		<tr class="table-info">
        		<th width="180" height="20">
					ジャンル検索
				</th>
				</tr>
			</thead>
		</table>
		<table frame="box">
			<tbody>
				<% @genres.each do |genre| %>
				<tr class="table-light">
					<td width="180" height="60">
						<%= link_to  products_path(genre_id: genre.id) do %>
						<%= genre.genre_name %>
						<% end%>
				<% end %>
					</td>
				</tr>
    		</tbody>
  		</table>
  	</div>

	<div class="col-sm-10">
		<ul class="list-inline">
			<li class="list-inline-item">
				<h3><strong><%= @products_name %>一覧</h3></strong>
			</li>
			<li class="list-inline-item">
				<h5>(全<%= @products.total_count %>件)</h5>
			</li>
		</ul>
		<div class="row">
			<% @products.each do |product| %>
			<div class="indexnewbox">
  				<div class="list p-2 my-2">
  					<%= link_to product_path(product.id) do %>
					<%= attachment_image_tag product, :image, :fill, 200, 100, format: 'jpeg'%>
					<% end %><br>
					<strong><%= link_to product.name, product_path(product) %></strong><br>
					<strong>¥<%= product.non_taxed_price.to_s(:delimited)%></strong>
				</div>
			</div>
			<% end %>
		</div>
	</div>
</div>

<div>
	<%= paginate @products %>
</div>

app/views/products/show.html.erb
<div class="row">
	<div class="col-sm-2 mt-4">
		<table border="1">
    		<thead>
        		<tr class="table-info">
        		<th width="180" height="20">
					ジャンル検索
				</th>
				</tr>
			</thead>
		</table>
		<table frame="box">
			<tbody>
				<% @genres.each do |genre| %>
				<tr class="table-light">
					<td width="180" height="60">
						<%= link_to  products_path(genre_id: genre.id) do %>
						<%= genre.genre_name %>
						<% end%>
				<% end %>
					</td>
				</tr>
    		</tbody>
  		</table>
  	</div>
	<div class ="col-sm-5 mt-5 px-5">
				<%= attachment_image_tag @product, :image, :fill, 350, 180, format: 'jpeg'%>
	</div>

	<div class ="col-sm-5 mt-5">
				<h3><strong><%= @product.name %></strong></h3><br>
				<p><%= @product.introduction %></p><br>
				<ul class="list-inline">
					<li class="list-inline-item">
					<strong><h3>¥<%= addTax(@product.non_taxed_price,1.10) %></h3></strong></li>
					<li class="list-inline-item">
					<font style="font-size:small">(税込)</font><br></li>
				</ul>
			<div class="form-inline mt-4">
				<% if customer_signed_in? %>
				<div align="right">
				<%= form_with model: @cart_product, url: cart_products_path(product_id: @product.id), method: :post, local: true do |f| %>
					<%= f.number_field :quantity, min:1, step: 1, placeholder: "個数選択", class: "form-control col-sm-4" %>
					<%= f.hidden_field :product_id, :value => @product.id %>
					<%= f.submit('カートに入れる',class: "btn btn-primary") %>
				<% end %>
				</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/products/top.html.erb
<div class="row">
	<div class="col-sm-2 mt-4">
		<table border="1">
    		<thead>
        		<tr class="table-info">
        		<th width="180" height="20">
					ジャンル検索
				</th>
				</tr>
			</thead>
		</table>
		<table frame="box">
			<tbody>
				<% @genres.each do |genre| %>
				<tr class="table-light">
					<td width="180" height="60">
						<%= link_to  products_path(genre_id: genre.id) do %>
						<%= genre.genre_name %>
						<% end%>
				<% end %>
					</td>
				</tr>
    		</tbody>
  		</table>
  	</div>

	<div class="col-sm-10 ">
		<strong>
  		<div class="jumbotron jumbotron-fluid text-white text-left pl-5 mt-4">
    			ようこそ、NaganoCakeへ！<br>このサイトは、ケーキ販売のECサイトになります。<br>会員でない方も商品の閲覧はできますが、<br>購入には会員登録が必要になります。
    	</div>
  		<strong>
		<h3>オススメ商品</h3>
		</strong>
		<div class="row">
			<% @products.each do |product| %>
			<div class="topnewbox">
  				<div class="list p-2 my-2">
  					<%= link_to product_path(product.id) do %>
					<%= attachment_image_tag product, :image, :fill, 200, 100, format: 'jpeg'%>
					<% end %><br>
					<%= link_to product.name, product_path(product.id) %><br>
					¥<%= product.non_taxed_price %>
				</div>
			</div>
			<% end %>
		</div>
			<div class="col-11 sm-11">
				<div class="text-right">
				<%= link_to products_path do %>
  				<p><u>もっと見る></u></p>
				<% end %>
				</div>
			</div>
	</div>
</div>