config/routes.rb
Rails.application.routes.draw do
  # デバイス
  devise_for :customers, skip: :all
  devise_scope :customer do
    get '/customers/sign_in', to: 'customers/sessions#new'
    post '/customers/sign_in', to: 'customers/sessions#create'
    delete '/customers/sign_out', to: 'customers/sessions#destroy'
    get '/customers/sign_up', to: 'customers/registrations#new'
    post '/customers', to: 'customers/registrations#create'
    get '/password/edit', to: 'customers/registrations#edit'
    put '/password/update', to: 'customers/passwords#update'
  end

  #ルート設定
  root "products#top"

  #顧客
  resource :customers, only: [:show,:edit,:update] do
    get :leave, on: :collection
    patch :left, on: :member
  end
  namespace :admin do
    resources :customers, only: [:index,:show,:edit,:update]
  end

  #管理者ログイン
  namespace :admin do
    get '/sign_in', to: 'admin#new'
    post '/sign_in', to: 'admin#create'
    delete '/sign_out', to: 'admin#destroy'
    get '/', to: 'admin#index'
  end

  #商品
  resources :products, only: [:index,:show] do
    get :top, on: :collection
  end
  namespace :admin do
    resources :products, only: [:index,:new,:show,:edit,:create,:update]
  end

  #配送先
  resources :ships, only: [:index,:edit,:update,:create,:destroy]

  #ジャンル
  namespace :admin do
    resources :genres, only: [:index,:edit,:update,:create]
  end

  #カートの商品
  post '/cart_products', to: 'cart_products#add'
  resources :cart_products, only: [:index,:destroy,:update] do
    delete :destroy_all, on: :collection
  end

  # 注文
  resources :orders, only: [:index,:show,:new,:create] do
    post :confirmation, action: :confirmation_new, on: :new
    get :complete, on: :collection
  end
  namespace :admin do
    resources :orders, only: [:index,:show,:update]
    patch '/order_products/:id', to: 'orders#products_update'
  end

  # 検索コーナー
  namespace :admin do
    get 'search/index', as: 'search'
  end



end

app/controllers/admin/search_controller.rb
class Admin::SearchController < ApplicationController
  before_action :authenticate_admin

  def index
    content = params[:search][:content]
    if content.present?
      @genres = Genre.where('genre_name LIKE ?', "%#{content}%")
      @products = Product.where('name LIKE ?', "%#{content}%")
      @customers = Customer.where(['last_name || first_name LIKE ? OR kana_last_name || kana_first_name LIKE ?', "%#{content}%", "%#{content}%"])
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/views/admin/search/_customer.html.erb
<div class="row">
  <div class="col-md-2 offset-md-1">
    <h5><span>会員</span></h5>
  </div>
</div>
<div class="row">
  <div class="col-md-8 offset-md-2">
    <table class="table">
      <thead>
        <tr  class="table-info">
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr class="table-light">
          <td><%= customer.id %></td>
          <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer) %></td>
          <td><%= customer.email %></td>
          <td><%= status(customer.is_valid) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/search/_genre.html.erb
<div class="row">
  <div class="col-md-2 offset-md-1">
    <h5><span>ジャンル</span></h5>
  </div>
</div>
<div class="row">
  <div class="col-md-8 offset-md-2">
    <table class="table">
      <thead>
        <tr class="table-info">
          <th>ジャンルID</th>
          <th>ジャンル名</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% genres.each do |genre| %>
          <tr class="table-light">
            <td><%= genre.id %></td>
            <td><%= link_to genre.genre_name, admin_genres_path(genre.id) %></td>
            <td><%= status(genre.is_valid) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/search/_product.html.erb
<div class="row">
  <div class="col-md-2 offset-md-1">
    <h5><span>製品</span></h5>
  </div>
</div>
<div class="row">
  <div class="col-md-8 offset-md-2">
    <table class="table">
      <thead>
        <tr class="table-info">
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% products.each do |product| %>
          <tr class ="table-light">
            <td><%= product.id %></td>
            <td><%= link_to product.name, admin_product_path(product.id) %></td>
            <td><%= converting_to_jpy(product.non_taxed_price) %></td>
            <td><%= product.genre.genre_name %></td>
            <td><%= sales(product.has_sold) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/search/index.html.erb
<div class="row">
  <div class="col-sm">
    <h6>検索ワード    "<%= params[:search][:content] %>"</h6>
    <!-- 顧客と商品とジャンルがヒット -->
    <% if @products.present? && @customers.present? && @genres.present? %>

      <!-- 商品 -->
      <%= render 'product', products: @products %>

      <!-- 顧客 -->
      <%= render 'customer', customers: @customers %>

      <!-- ジャンル -->
      <%= render 'genre', genres: @genres %>

      <!-- 顧客と商品がヒット -->
    <% elsif @products.present? && @customers.present? && @genres.blank? %>

      <!-- 商品 -->
      <%= render 'product', products: @products %>

      <!-- 顧客 -->
      <%= render 'customer', customers: @customers %>


      <!-- 顧客とジャンルがヒット -->
    <% elsif @products.blank? && @customers.present? && @genres.present? %>

      <!-- 商品 -->
      <%= render 'product', products: @products %>

      <!-- ジャンル -->
      <%= render 'genre', customers: @genres %>

      <!-- ジャンルと商品がヒット -->
    <% elsif @products.present? && @customers.blank? && @genres.present? %>

      <!-- 商品 -->
      <%= render 'product', products: @products %>

      <!-- ジャンル -->
      <%= render 'genre', genres: @genres %>

    <!-- 商品のみヒット -->
    <% elsif @products.present? && @customers.blank? && @genres.blank? %>
      <!-- 商品 -->
      <%= render 'product', products: @products %>

    <!-- 顧客のみヒット -->
    <% elsif @products.blank? && @customers.present? && @genres.blank? %>

      <!-- 顧客 -->
      <%= render 'customer', customers: @customers %>

    <!-- ジャンルのみヒット -->
    <% elsif @products.blank? && @customers.blank? && @genres.present? %>

      <!-- ジャンル -->
      <%= render 'genre', genres: @genres %>

    <!-- どちらもヒットせず -->
    <% else @products.blank? && @customers.blank? && @genres.blank? %>
      <h4>検索結果が見つかりませんでした</h4>

    <% end %>

  </div>
</div>